name: Checkout

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
